name: 'Jenkins Job Trigger'
description: 'Trigger a Jenkins job'
branding:
  icon: 'terminal'
  color: 'green'
inputs:
  url: 'https://e115-2405-201-402e-a021-1080-420b-cfb8-b637.ngrok-free.app/'
    description: 'Jenkins full URL including http/https protocol'
    required: true
  user_name: 'admin'
    description: 'User name of Jenkins'
    required: true
  api_token: '11b6ffe3702b9ce4c2cfcc1b9ed6a96d78'
    description: 'Jenkins API token'
    required: true
  job_name: 'sample4'
    description: 'Job name'
    required: true
  parameter: 
    description: 'Job parameter in JSON format. ex) {"param1":"value1"} '
    required: false
  headers:
    description: 'Additional headers to include in the HTTP requests in JSON format. ex) {"param1":"value1"} '
    required: false
  wait:
    description: 'Waiting for job completion or not'
    required: false
    default: "true"
  timeout:
    description: 'Timeout (seconds) for github action. Set 600s as default'
    required: false
    default: "600"
  
runs:
  using: 'node12'
  main: 'index.js'
