name: Trigger jenkins job
  branding:
    icon: 'terminal'
    color: 'green'
  uses: jabbukka/jenkins-trigger@main
  with:
    url: 'https://e115-2405-201-402e-a021-1080-420b-cfb8-b637.ngrok-free.app/'
    job_name: 'sample4'
    user_name: 'admin'
    api_token: '11b6ffe3702b9ce4c2cfcc1b9ed6a96d78'
    wait: "true"
    timeout: "1000"
